version: '2'
services:
    spgserver-app:
        image: spgserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://spgserver-mysql:3306/spgserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    spgserver-mysql:
        extends:
            file: mysql.yml
            service: spgserver-mysql
